"""Value tests for the hand-written interpreted VDIA+VBR+CSR kernels.

Each test compiles ``interpreted/interp_vdia_vbr_csr_{spmv,spmm}.c``, runs it on a
fixture matrix (the binary prints its result vector when passed a trailing ``y``
argument), and compares the result against a NumPy reference for the same matrix
and RHS.  Both CSR backends (naive, mkl) are exercised.

These are value (numerical) tests only.  There are intentionally NO golden /
text-snapshot tests for the hand-written interpreted kernels -- they are not
generated by SABLE's codegen, so a NumPy comparison is the right check.  (The
``*_interp.c`` golden fixtures elsewhere are for SABLE's separate
``plan.interpret()`` framework mode, not these files.)

Requires gcc and MKL (the interpreted kernels use cblas/MKL for VBR and the mkl
CSR backend).
"""

import os
import pathlib
import shutil
import subprocess

import numpy
import pytest

from sable.build_config import MKL_AVAILABLE, MKL_FLAGS
from interpreted.make_data import build_vdia_matrix, write_dense, write_vdia_sabledata

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
INTERP_DIR = REPO_ROOT / "interpreted"

pytestmark = pytest.mark.skipif(
    shutil.which("gcc") is None or not MKL_AVAILABLE,
    reason="requires gcc and MKL",
)


def _compile(source_name: str, out_dir: pathlib.Path) -> pathlib.Path:
    binary = out_dir / source_name.replace(".c", "")
    subprocess.run(
        ["gcc", "-O2", "-o", str(binary), str(INTERP_DIR / source_name), *MKL_FLAGS],
        check=True,
        capture_output=True,
        text=True,
    )
    return binary


def _run_values(binary: pathlib.Path, data_path, rhs_path, csr_backend) -> numpy.ndarray:
    env = {**os.environ, "MKL_THREADING_LAYER": "GNU"}
    out = subprocess.check_output(
        [str(binary), str(data_path), str(rhs_path), csr_backend, "y"], text=True, env=env
    )
    return numpy.array([float(v) for v in out.split() if v.strip()])


@pytest.mark.parametrize("csr_backend", ["naive", "mkl"])
def test_interp_vdia_vbr_csr_spmv(tmp_path, csr_backend):
    A = build_vdia_matrix()
    data_path = tmp_path / "fixture_vdia.sabledata"
    write_vdia_sabledata(str(data_path), A)

    x = numpy.random.default_rng(0).standard_normal(A.shape[1])
    rhs_path = tmp_path / "x.vector"
    write_dense(str(rhs_path), x)

    binary = _compile("interp_vdia_vbr_csr_spmv.c", tmp_path)
    y = _run_values(binary, data_path, rhs_path, csr_backend)
    numpy.testing.assert_allclose(y, A @ x, rtol=1e-12, atol=1e-9)


@pytest.mark.parametrize("csr_backend", ["naive", "mkl"])
@pytest.mark.parametrize("nrhs", [1, 4, 7])
def test_interp_vdia_vbr_csr_spmm(tmp_path, csr_backend, nrhs):
    A = build_vdia_matrix()
    data_path = tmp_path / "fixture_vdia.sabledata"
    write_vdia_sabledata(str(data_path), A)

    X = numpy.random.default_rng(nrhs).standard_normal((A.shape[1], nrhs))
    rhs_path = tmp_path / "x.matrix"
    write_dense(str(rhs_path), X)

    binary = _compile("interp_vdia_vbr_csr_spmm.c", tmp_path)
    y = _run_values(binary, data_path, rhs_path, csr_backend)
    numpy.testing.assert_allclose(y, (A @ X).reshape(-1), rtol=1e-12, atol=1e-9)
